### ISSUE TITLE
TypeError in buttonsAndMessages

### ISSUE THREAD

**Issue by eroux** [France-ioi/bebras-modules#3]
I have this error line 273 in buttonsAndMessages, on [this link](http://jls.algorea.org/contents/4207%252F4202%252F1304077337136889964?sell=2):

```
Uncaught TypeError: Cannot read property 'addClass' of null(…)(anonymous function) 
@ buttonsAndMessages.js:273 onMessage 
@ jschannel.js:493 s_onMessage 
@ jschannel.js:195
```

**Comment by nir-lavee** [comment]
It seems that the `difficultyWarning` field should be translated to all languages in order to work correctly (currently it only exists in `displayHelper.languageStrings.fr`), regardless of whether it's used or not.

**Comment by eroux** [comment]
I've just translatted it into English, translating into German is not something I can do...

**Comment by eroux** [comment]
adding the German version fixed the error
